import {
  Document,
  Font,
  Image,
  Page,
  StyleSheet,
  Text,
  View,
} from '@react-pdf/renderer';
import React from 'react';

import type {
  AttendanceReportData,
  AttendanceReportLocale,
  AttendanceReportRow,
} from '@/lib/attendance-report';
import { hasArabic } from '@/lib/attendance-report';

// Font registration is performed by the API route before calling renderToBuffer.
// Disable hyphenation here so it applies whenever fonts are registered.
Font.registerHyphenationCallback((word) => [word]);

// ─── Brand tokens ─────────────────────────────────────────────────────────────

const BRAND = {
  blue: '#34AAE1',
  gold: '#F8B548',
  navy: '#123047',
  graphite: '#2F3A45',
  lightBlue: '#EAF7FD',
  lightGold: '#FFF4DF',
  border: '#E5E7EB',
  white: '#FFFFFF',
  pageBg: '#F8FAFC',
  rowAlt: '#F4F8FB',
  green: '#16A34A',
  red: '#DC2626',
  amber: '#D97706',
  orange: '#EA580C',
  gray: '#6B7280',
};

// ─── Layout constants ─────────────────────────────────────────────────────────

// A4 landscape: 841.89 × 595.28 pt
const PAGE_PAD_H = 30;   // left + right
const PAGE_PAD_V_BOTTOM = 32;
const FOOTER_H = 22;
const TABLE_PAGE_BANNER_H = 34;  // compact repeating header on every page
const TABLE_HEADER_H = 22;       // column header row

// Manual page chunks keep employee rows intact and repeat the table header.
const FIRST_PAGE_ROW_LIMIT = 20;
const CONTINUATION_PAGE_ROW_LIMIT = 25;

// Column widths (pt) — total ≈ 782 (= 841.89 - 60 padding)
const COL = {
  index:      18,
  employee:  128,
  branch:     83,
  date:       65,
  shift:      65,
  checkIn:    48,
  checkOut:   48,
  late:       38,
  earlyLeave: 42,
  overtime:   38,
  status:     74,
  location:  135,
} as const;

const FONT_SM = 6.5;
const FONT_BASE = 7.5;
const PDF_COPY = {
  en: {
    reportTitle: 'Amwag Travel — Attendance Daily Report',
    documentAuthor: 'Amwag Travel Attendance System',
    documentCreator: 'Amwag Attendance System',
    metadata: {
      period: 'Period',
      generatedBy: 'Generated By',
      generatedAt: 'Generated At',
      branch: 'Branch',
      employee: 'Employee',
      allDates: 'All Dates',
      to: 'to',
    },
    kpis: {
      totalRecords: 'Total Records',
      present: 'Present',
      absent: 'Absent',
      late: 'Late',
      earlyLeave: 'Early Leave',
      missingCheckout: 'No Checkout',
      overtime: 'Overtime',
    },
    columns: {
      index: '#',
      employee: 'Employee',
      branch: 'Branch',
      date: 'Date',
      shift: 'Shift',
      checkIn: 'Check In',
      checkOut: 'Check Out',
      late: 'Late',
      earlyLeave: 'Early Leave',
      overtime: 'Overtime',
      status: 'Status',
      location: 'Location',
    },
    status: {
      present: 'PRESENT',
      late: 'LATE',
      absent: 'ABSENT',
      missing_checkout: 'NO CHECKOUT',
      pending: 'PENDING',
    },
    footer: {
      system: 'Amwag Travel Attendance System',
      poweredBy: 'Powered by Abdelhmeed Elshorbagy',
      page: (pageNumber: number, totalPages: number) => `Page ${pageNumber} of ${totalPages}`,
    },
    empty: {
      title: 'No Attendance Records Found',
      subtitle: 'No records match the selected filters. Please adjust your search criteria.',
    },
  },
  ar: {
    reportTitle: 'أمواج للسياحة - تقرير الحضور اليومي',
    documentAuthor: 'نظام حضور أمواج للسياحة',
    documentCreator: 'نظام حضور أمواج',
    metadata: {
      period: 'الفترة',
      generatedBy: 'تم الإنشاء بواسطة',
      generatedAt: 'وقت الإنشاء',
      branch: 'الفرع',
      employee: 'الموظف',
      allDates: 'كل التواريخ',
      to: 'إلى',
    },
    kpis: {
      totalRecords: 'إجمالي السجلات',
      present: 'حاضر',
      absent: 'غائب',
      late: 'متأخر',
      earlyLeave: 'انصراف مبكر',
      missingCheckout: 'انصراف مفقود',
      overtime: 'إضافي',
    },
    columns: {
      index: '#',
      employee: 'الموظف',
      branch: 'الفرع',
      date: 'التاريخ',
      shift: 'الوردية',
      checkIn: 'الحضور',
      checkOut: 'الانصراف',
      late: 'التأخير',
      earlyLeave: 'الانصراف المبكر',
      overtime: 'الإضافي',
      status: 'الحالة',
      location: 'الموقع',
    },
    status: {
      present: 'حاضر',
      late: 'متأخر',
      absent: 'غائب',
      missing_checkout: 'انصراف مفقود',
      pending: 'في الانتظار',
    },
    footer: {
      system: 'نظام حضور أمواج للسياحة',
      poweredBy: 'تم الإنشاء بواسطة عبدالحميد الشوربجي',
      page: (pageNumber: number, totalPages: number) => `صفحة ${pageNumber} من ${totalPages}`,
    },
    empty: {
      title: 'لا توجد سجلات حضور',
      subtitle: 'لا توجد سجلات مطابقة للمرشحات المحددة. يرجى تعديل معايير البحث.',
    },
  },
} as const;

function getCopy(locale: AttendanceReportLocale) {
  return PDF_COPY[locale];
}

// ─── Grid / row shading (Excel-style) ────────────────────────────────────────

const GRID = '#D4DEE7';          // cell divider lines
const ROW_BG_A = '#F4F8FB';      // odd rows (soft blue/gray)
const ROW_BG_B = BRAND.white;    // even rows

function rowBg(rowIndex: number): string {
  return rowIndex % 2 === 0 ? ROW_BG_A : ROW_BG_B;
}

function bodyCell(rowIndex: number, i: number, width: number) {
  return {
    width,
    backgroundColor: rowBg(rowIndex),
    paddingHorizontal: 3,
    paddingVertical: 3,
    borderRightWidth: 0.5,
    borderRightColor: GRID,
    borderLeftWidth: i === 0 ? 0.5 : 0,
    borderLeftColor: GRID,
  };
}

function headerCell(i: number, width: number) {
  return {
    width,
    paddingHorizontal: 3,
    justifyContent: 'center' as const,
    borderRightWidth: 0.5,
    borderRightColor: GRID,
    borderLeftWidth: i === 0 ? 0.5 : 0,
    borderLeftColor: GRID,
  };
}

// ─── StyleSheet ──────────────────────────────────────────────────────────────

const s = StyleSheet.create({
  // ── Report pages ─────────────────────────────
  reportPage: {
    backgroundColor: BRAND.white,
    paddingTop: TABLE_PAGE_BANNER_H + 8,
    paddingBottom: PAGE_PAD_V_BOTTOM + FOOTER_H,
    paddingHorizontal: PAGE_PAD_H,
    fontFamily: 'Helvetica',
    fontSize: FONT_BASE,
    color: BRAND.graphite,
  },
  reportPageArabic: {
    fontFamily: 'Amiri',
    direction: 'rtl',
  },

  // ── Report metadata (first page) ─────────────
  reportMetaSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 6,
    marginBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: BRAND.border,
  },
  metaBlock: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 2,
  },
  metaBlockArabic: {
    flexDirection: 'row-reverse',
  },
  metaLine: {
    fontSize: FONT_SM,
    color: BRAND.graphite,
    marginRight: 12,
  },
  metaLineArabic: {
    marginRight: 0,
    marginLeft: 12,
    fontFamily: 'Amiri',
    textAlign: 'right',
  },
  metaLabel: {
    fontFamily: 'Helvetica-Bold',
    color: BRAND.navy,
  },
  metaLabelArabic: {
    fontFamily: 'Amiri',
  },
  metaValueArabic: {
    fontFamily: 'Amiri',
    fontSize: FONT_BASE,
  },

  // ── KPI cards ────────────────────────────────
  kpiSection: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 8,
  },
  kpiSectionArabic: {
    flexDirection: 'row-reverse',
  },
  kpiCard: {
    flex: 1,
    backgroundColor: BRAND.white,
    borderRadius: 4,
    border: `1 solid ${BRAND.border}`,
    padding: 6,
  },
  kpiAccentLine: {
    height: 2,
    borderRadius: 1,
    width: 20,
    marginBottom: 5,
  },
  kpiLabel: {
    fontSize: 5.5,
    fontFamily: 'Helvetica-Bold',
    color: BRAND.gray,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  kpiLabelArabic: {
    fontFamily: 'Amiri',
    textAlign: 'right',
    textTransform: 'none',
    letterSpacing: 0,
  },
  kpiValue: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    marginTop: 3,
  },
  kpiValueArabic: {
    fontFamily: 'Amiri',
    textAlign: 'right',
  },

  // ── Compact repeating banner (table pages) ───
  tableBanner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: TABLE_PAGE_BANNER_H,
    backgroundColor: BRAND.navy,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: PAGE_PAD_H,
  },
  tableBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  tableBannerLeftArabic: {
    flexDirection: 'row-reverse',
  },
  tableBannerLogo: {
    width: 20,
    height: 20,
    objectFit: 'contain',
  },
  tableBannerTitle: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: BRAND.white,
    letterSpacing: 0.3,
  },
  tableBannerTitleArabic: {
    fontFamily: 'Amiri',
    letterSpacing: 0,
  },
  // ── Table header ─────────────────────────────
  tableHeaderRow: {
    height: TABLE_HEADER_H,
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: BRAND.navy,
    borderBottomWidth: 2,
    borderBottomColor: BRAND.gold,
  },
  tableHeaderRowArabic: {
    flexDirection: 'row-reverse',
  },
  thCell: {
    fontSize: 5.5,
    fontFamily: 'Helvetica-Bold',
    color: BRAND.white,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  thCellArabic: {
    fontFamily: 'Amiri',
    textAlign: 'right',
    textTransform: 'none',
    letterSpacing: 0,
  },
  tableBody: {
    borderLeftWidth: 0.5,
    borderLeftColor: GRID,
  },

  // ── Table rows ───────────────────────────────
  tableRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    minHeight: 18,
    borderBottomWidth: 0.5,
    borderBottomColor: GRID,
  },
  tableRowArabic: {
    flexDirection: 'row-reverse',
  },
  tdCell: {
    fontSize: FONT_SM,
    color: BRAND.graphite,
    flexWrap: 'wrap',
  },
  tdCellArabic: {
    fontFamily: 'Amiri',
    fontSize: FONT_BASE,
  },
  tdCellTwoLine: {
    maxLines: 2,
  },

  // ── Status badge ─────────────────────────────
  badge: {
    borderRadius: 3,
    paddingHorizontal: 4,
    paddingVertical: 2,
    alignSelf: 'flex-start',
  },
  badgeText: {
    fontSize: 5.5,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.2,
  },
  badgeTextArabic: {
    fontFamily: 'Amiri',
    letterSpacing: 0,
  },

  // ── Footer ───────────────────────────────────
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: FOOTER_H,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: PAGE_PAD_H,
    borderTopWidth: 0.5,
    borderTopColor: BRAND.border,
    backgroundColor: BRAND.white,
  },
  footerText: {
    fontSize: 6,
    color: BRAND.gray,
  },
  footerTextArabic: {
    fontFamily: 'Amiri',
  },
  footerSlotLeft: {
    flex: 1,
    alignItems: 'flex-start',
  },
  footerSlotCenter: {
    flex: 1,
    alignItems: 'center',
  },
  footerSlotRight: {
    flex: 1,
    alignItems: 'flex-end',
  },

  // ── Empty state ──────────────────────────────
  emptyBox: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  emptyTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: BRAND.navy,
  },
  emptyTitleArabic: {
    fontFamily: 'Amiri',
  },
  emptySubtitle: {
    fontSize: FONT_BASE,
    color: BRAND.gray,
  },
  emptySubtitleArabic: {
    fontFamily: 'Amiri',
  },
});

// ─── Status badge ─────────────────────────────────────────────────────────────

type StatusKey = AttendanceReportRow['status'];

const STATUS_STYLE: Record<StatusKey, { bg: string; text: string }> = {
  present:          { bg: '#DCFCE7', text: BRAND.green },
  late:             { bg: BRAND.lightGold, text: BRAND.amber },
  absent:           { bg: '#FEE2E2', text: BRAND.red },
  missing_checkout: { bg: '#FFEDD5', text: BRAND.orange },
  pending:          { bg: '#F3F4F6', text: BRAND.gray },
};

function StatusBadge({ status, locale }: { status: StatusKey; locale: AttendanceReportLocale }) {
  const cfg = STATUS_STYLE[status] ?? STATUS_STYLE.pending;
  const label = getCopy(locale).status[status] ?? getCopy(locale).status.pending;
  return (
    <View style={[s.badge, { backgroundColor: cfg.bg }]}>
      <Text style={[
        s.badgeText,
        locale === 'ar' ? s.badgeTextArabic : {},
        { color: cfg.text },
      ]}>
        {label}
      </Text>
    </View>
  );
}

// ─── KPI section ─────────────────────────────────────────────────────────────

const KPI_CONFIG = [
  { key: 'totalRecords' as const, color: BRAND.navy },
  { key: 'present'     as const, color: BRAND.green },
  { key: 'absent'      as const, color: BRAND.red },
  { key: 'late'        as const, color: BRAND.amber },
  { key: 'earlyLeave'  as const, color: BRAND.orange },
  { key: 'missingCheckout' as const, color: BRAND.orange },
  { key: 'overtime'    as const, color: BRAND.blue },
];

function KpiSection({
  summary,
  locale,
}: {
  summary: AttendanceReportData['summary'];
  locale: AttendanceReportLocale;
}) {
  const copy = getCopy(locale);
  return (
    <View style={[s.kpiSection, locale === 'ar' ? s.kpiSectionArabic : {}]}>
      {KPI_CONFIG.map(({ key, color }) => (
        <View key={key} style={s.kpiCard}>
          <View style={[s.kpiAccentLine, { backgroundColor: color }]} />
          <Text style={[s.kpiLabel, locale === 'ar' ? s.kpiLabelArabic : {}]}>
            {copy.kpis[key]}
          </Text>
          <Text style={[s.kpiValue, locale === 'ar' ? s.kpiValueArabic : {}, { color }]}>
            {summary[key]}
          </Text>
        </View>
      ))}
    </View>
  );
}

// ─── Footer ───────────────────────────────────────────────────────────────────

function Footer({
  pageNumber,
  totalPages,
  locale,
}: {
  pageNumber: number;
  totalPages: number;
  locale: AttendanceReportLocale;
}) {
  const copy = getCopy(locale);
  const footerTextStyle = [s.footerText, locale === 'ar' ? s.footerTextArabic : {}];
  return (
    <View style={s.footer} fixed>
      <View style={s.footerSlotLeft}>
        <Text style={footerTextStyle}>{copy.footer.system}</Text>
      </View>
      <View style={s.footerSlotCenter}>
        <Text style={footerTextStyle}>{copy.footer.poweredBy}</Text>
      </View>
      <View style={s.footerSlotRight}>
        <Text style={footerTextStyle}>{copy.footer.page(pageNumber, totalPages)}</Text>
      </View>
    </View>
  );
}

export function getAttendancePdfFooterTextsForTest(
  pageNumber: number,
  totalPages: number,
  locale: AttendanceReportLocale = 'en',
) {
  const copy = getCopy(locale);
  return [
    copy.footer.system,
    copy.footer.poweredBy,
    copy.footer.page(pageNumber, totalPages),
  ];
}

// ─── Table column header ─────────────────────────────────────────────────────

const COLUMNS: Array<{ key: keyof typeof PDF_COPY.en.columns; width: number }> = [
  { key: 'index',      width: COL.index },
  { key: 'employee',   width: COL.employee },
  { key: 'branch',     width: COL.branch },
  { key: 'date',       width: COL.date },
  { key: 'shift',      width: COL.shift },
  { key: 'checkIn',    width: COL.checkIn },
  { key: 'checkOut',   width: COL.checkOut },
  { key: 'late',       width: COL.late },
  { key: 'earlyLeave', width: COL.earlyLeave },
  { key: 'overtime',   width: COL.overtime },
  { key: 'status',     width: COL.status },
  { key: 'location',   width: COL.location },
];

function TableColumnHeader({ locale }: { locale: AttendanceReportLocale }) {
  const copy = getCopy(locale);
  return (
    <View style={[s.tableHeaderRow, locale === 'ar' ? s.tableHeaderRowArabic : {}]}>
      {COLUMNS.map((col, i) => (
        <View key={col.key} style={headerCell(i, col.width)}>
          <Text style={[s.thCell, locale === 'ar' ? s.thCellArabic : {}]}>
            {copy.columns[col.key]}
          </Text>
        </View>
      ))}
    </View>
  );
}

// ─── Table row ────────────────────────────────────────────────────────────────

function tdStyle(text: string, locale: AttendanceReportLocale) {
  return locale === 'ar' || hasArabic(text)
    ? [s.tdCell, s.tdCellArabic]
    : [s.tdCell];
}

function TableDataRow({
  row,
  locale,
}: {
  row: AttendanceReportRow;
  locale: AttendanceReportLocale;
}) {
  const rowIndex = Math.max(0, row.index - 1);

  return (
    <View style={[s.tableRow, locale === 'ar' ? s.tableRowArabic : {}]} wrap={false}>
      <View style={bodyCell(rowIndex, 0, COL.index)}>
        <Text style={s.tdCell}>{row.index}</Text>
      </View>
      <View style={bodyCell(rowIndex, 1, COL.employee)}>
        <Text style={[...tdStyle(row.employeeName, locale), s.tdCellTwoLine]}>{row.employeeName}</Text>
      </View>
      <View style={bodyCell(rowIndex, 2, COL.branch)}>
        <Text style={[...tdStyle(row.branch, locale), s.tdCellTwoLine]}>{row.branch}</Text>
      </View>
      <View style={bodyCell(rowIndex, 3, COL.date)}>
        <Text style={s.tdCell}>{row.date}</Text>
      </View>
      <View style={bodyCell(rowIndex, 4, COL.shift)}>
        <Text style={s.tdCell}>{row.shift}</Text>
      </View>
      <View style={bodyCell(rowIndex, 5, COL.checkIn)}>
        <Text style={s.tdCell}>{row.checkIn}</Text>
      </View>
      <View style={bodyCell(rowIndex, 6, COL.checkOut)}>
        <Text style={s.tdCell}>{row.checkOut}</Text>
      </View>
      <View style={bodyCell(rowIndex, 7, COL.late)}>
        <Text style={s.tdCell}>{row.late}</Text>
      </View>
      <View style={bodyCell(rowIndex, 8, COL.earlyLeave)}>
        <Text style={s.tdCell}>{row.earlyLeave}</Text>
      </View>
      <View style={bodyCell(rowIndex, 9, COL.overtime)}>
        <Text style={s.tdCell}>{row.overtime}</Text>
      </View>
      <View style={bodyCell(rowIndex, 10, COL.status)}>
        <StatusBadge status={row.status} locale={locale} />
      </View>
      <View style={bodyCell(rowIndex, 11, COL.location)}>
        <Text style={[...tdStyle(row.location, locale), s.tdCellTwoLine]}>{row.location}</Text>
      </View>
    </View>
  );
}

export function getAttendancePdfRowStyleForTest(rowIndex: number, columnIndex: number) {
  return bodyCell(rowIndex, columnIndex, 1);
}

export function getAttendancePdfHeaderCellStyleForTest(columnIndex: number, width: number) {
  return headerCell(columnIndex, width);
}

// ─── Report page layout ──────────────────────────────────────────────────────

type AttendancePdfPage = {
  pageIndex: number;
  isFirstPage: boolean;
  rows: AttendanceReportRow[];
};

function periodLabel(data: AttendanceReportData, locale: AttendanceReportLocale): string {
  const { filters } = data;
  if (filters.dateRangeLabel) return filters.dateRangeLabel;
  const copy = getCopy(locale);
  if (filters.dateFilter) return `${filters.dateFilter} ${copy.metadata.to} ${filters.dateFilter}`;
  return copy.metadata.allDates;
}

function metadataValueStyle(text: string, locale: AttendanceReportLocale = 'en') {
  return locale === 'ar' || hasArabic(text) ? s.metaValueArabic : {};
}

function paginateRows(rows: AttendanceReportRow[]): AttendancePdfPage[] {
  if (rows.length === 0) {
    return [{ pageIndex: 0, isFirstPage: true, rows: [] }];
  }

  const pages: AttendancePdfPage[] = [];
  pages.push({
    pageIndex: 0,
    isFirstPage: true,
    rows: rows.slice(0, FIRST_PAGE_ROW_LIMIT),
  });

  let offset = FIRST_PAGE_ROW_LIMIT;
  while (offset < rows.length) {
    pages.push({
      pageIndex: pages.length,
      isFirstPage: false,
      rows: rows.slice(offset, offset + CONTINUATION_PAGE_ROW_LIMIT),
    });
    offset += CONTINUATION_PAGE_ROW_LIMIT;
  }

  return pages;
}

export function getAttendancePdfPagesForTest(data: AttendanceReportData): AttendancePdfPage[] {
  return paginateRows(data.rows);
}

function ReportBanner({
  logoSrc,
  locale,
}: {
  logoSrc: string;
  locale: AttendanceReportLocale;
}) {
  const copy = getCopy(locale);
  return (
    <View style={s.tableBanner} fixed>
      <View style={[s.tableBannerLeft, locale === 'ar' ? s.tableBannerLeftArabic : {}]}>
        {logoSrc ? (
          // eslint-disable-next-line jsx-a11y/alt-text -- React PDF Image does not support alt.
          <Image style={s.tableBannerLogo} src={logoSrc} />
        ) : null}
        <Text style={[s.tableBannerTitle, locale === 'ar' ? s.tableBannerTitleArabic : {}]}>
          {copy.reportTitle}
        </Text>
      </View>
    </View>
  );
}

export function getAttendancePdfReportBannerTextsForTest(
  _data: AttendanceReportData,
  locale: AttendanceReportLocale = 'en',
): string[] {
  return [getCopy(locale).reportTitle];
}

export function getAttendancePdfMetadataValueStyleForTest(text: string) {
  return metadataValueStyle(text);
}

function MetadataLine({
  label,
  value,
  locale,
}: {
  label: string;
  value: string;
  locale: AttendanceReportLocale;
}) {
  return (
    <Text style={[s.metaLine, locale === 'ar' ? s.metaLineArabic : {}]}>
      <Text style={[s.metaLabel, locale === 'ar' ? s.metaLabelArabic : {}]}>{label}: </Text>
      <Text style={metadataValueStyle(value, locale)}>{value}</Text>
    </Text>
  );
}

function ReportMetadata({
  data,
  locale,
}: {
  data: AttendanceReportData;
  locale: AttendanceReportLocale;
}) {
  const { filters, meta } = data;
  const copy = getCopy(locale);
  const period = periodLabel(data, locale);

  return (
    <View style={s.reportMetaSection}>
      <View style={[s.metaBlock, locale === 'ar' ? s.metaBlockArabic : {}]}>
        <MetadataLine label={copy.metadata.period} value={period} locale={locale} />
        <MetadataLine label={copy.metadata.generatedBy} value={meta.generatedBy} locale={locale} />
        <MetadataLine label={copy.metadata.generatedAt} value={meta.generatedAt} locale={locale} />
        {filters.branchName && (
          <MetadataLine label={copy.metadata.branch} value={filters.branchName} locale={locale} />
        )}
        {filters.employeeName && (
          <MetadataLine label={copy.metadata.employee} value={filters.employeeName} locale={locale} />
        )}
      </View>
    </View>
  );
}

// ─── Report page ──────────────────────────────────────────────────────────────

function ReportPage({
  data,
  logoSrc,
  page,
  totalPages,
  locale,
}: {
  data: AttendanceReportData;
  logoSrc: string;
  page: AttendancePdfPage;
  totalPages: number;
  locale: AttendanceReportLocale;
}) {
  const copy = getCopy(locale);
  return (
    <Page
      size="A4"
      orientation="landscape"
      style={[s.reportPage, locale === 'ar' ? s.reportPageArabic : {}]}
    >
      <ReportBanner logoSrc={logoSrc} locale={locale} />

      {page.isFirstPage && (
        <>
          <ReportMetadata data={data} locale={locale} />
          <KpiSection summary={data.summary} locale={locale} />
        </>
      )}

      {page.rows.length > 0 && (
        <>
          <TableColumnHeader locale={locale} />
          <View style={s.tableBody}>
            {page.rows.map((row) => (
              <TableDataRow key={row.index} row={row} locale={locale} />
            ))}
          </View>
        </>
      )}

      {page.isFirstPage && data.rows.length === 0 && (
        <View style={s.emptyBox}>
          <Text style={[s.emptyTitle, locale === 'ar' ? s.emptyTitleArabic : {}]}>
            {copy.empty.title}
          </Text>
          <Text style={[s.emptySubtitle, locale === 'ar' ? s.emptySubtitleArabic : {}]}>
            {copy.empty.subtitle}
          </Text>
        </View>
      )}
      <Footer pageNumber={page.pageIndex + 1} totalPages={totalPages} locale={locale} />
    </Page>
  );
}

// ─── Document ─────────────────────────────────────────────────────────────────

export interface AttendanceReportPdfProps {
  data: AttendanceReportData;
  logoSrc: string;
  locale?: AttendanceReportLocale;
}

export function AttendanceReportPdf({ data, logoSrc, locale = 'en' }: AttendanceReportPdfProps) {
  const pages = paginateRows(data.rows);
  const copy = getCopy(locale);

  return (
    <Document
      title={copy.reportTitle}
      author={copy.documentAuthor}
      subject={`${copy.reportTitle} - ${data.filters.dateRangeLabel ?? data.filters.dateFilter ?? ''}`}
      creator={copy.documentCreator}
    >
      {pages.map((page) => (
        <ReportPage
          key={page.pageIndex}
          data={data}
          logoSrc={logoSrc}
          page={page}
          totalPages={pages.length}
          locale={locale}
        />
      ))}
    </Document>
  );
}
